Exercise5
Hareesh-Raj/Java pull request #6
Opened 2023-03-03 09:50 UTC by Hareesh-Raj

Added Exercise 5

2023-03-07 11:06 UTC, Adheesh-Sirius requested changes

2023-03-07 11:06 UTC, Adheesh-Sirius commented on Exercise5/BridgePattern.java
> +	protected Resturant(Pizza pizza)
Correct these minor spelling errors please

2023-03-07 11:06 UTC, Adheesh-Sirius commented on Exercise5/BridgePattern.java
> +	protected String sauce;
Any specific reason to declare the variables as `proctected`?

2023-03-07 15:47 UTC, Hareesh-Raj commented on Exercise5/BridgePattern.java
> +	protected String sauce;
Only the classes which inherits the pizza class only will have the access to the variable other than any class cannot be able to access the sauce.

2023-03-09 12:09 UTC, Adheesh-Sirius approved these changes

2023-03-09 12:10 UTC, merged